AWSTemplateFormatVersion: 2010-09-09
Description: >-
  "wp-rds"

Parameters:
  Env:
    Type: String
    Default: "dev"
    AllowedValues: ["dev", "stg", "prd"]
  ResourceName:
    Type: String
    Default: "WpProject"

  DBInstanceID:
    Type: String
    Default: db
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DBName:
    Type: String
    Default: wordpress
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DBUsername:
    Type: String
    Default: admin
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t2.micro
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Type: Number
    Default: 20
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
  DBEngineVersion:
    Type: String
    Default: 8.0.33

Resources:
  # ------------------------------ #
  # MySQLRDSInstance
  # ------------------------------ #
  MySQLRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: MySQL
      DBInstanceIdentifier: !Join ['-', [!Ref 'Env', !Ref 'ResourceName', !Ref 'DBInstanceID']]
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      EngineVersion: !Ref DBEngineVersion
      VPCSecurityGroups: 
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
  # ------------------------------ #
  # DBSecurityGroup
  # ------------------------------ #
  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupName: !Join ['-', [!Ref 'Env', !Ref 'ResourceName', 'sg-for-rds']]
      VpcId: !ImportValue WpVpc
      GroupDescription: Security group for RDSInstance
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue WpEC2SecurityGroup
          Description: Allow MySQL traffic from WpEC2SecurityGroup
      Tags: 
        - Key: Name
          Value: !Join ['-', [!Ref 'Env', !Ref 'ResourceName', 'sg-for-rds']]
  # ------------------------------ #
  # DBSubnetGroup
  # ------------------------------ #
  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: description
      DBSubnetGroupName: !Join ['-', [!Ref 'Env', !Ref 'ResourceName', 'DBSubnetGroup']]
      SubnetIds: 
        - !ImportValue 'WpPrivateSubnet1a'
        - !ImportValue 'WpPrivateSubnet1c'
      Tags: 
        - Key: String
          Value: !Join ['-', [!Ref 'Env', !Ref 'ResourceName', 'DBSubnetGroup']]
  # ------------------------------ #
  # SSM ParameterStore
  # ------------------------------ #
  DBNameParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: '/wordpress/WP_DB_NAME'
      Type: String
      Value: !Ref DBName
  DBUserParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: '/wordpress/WP_DB_USER'
      Type: String
      Value: !Ref DBUsername
  DBPasswordParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: '/wordpress/WP_DB_PASSWORD'
      Type: String
      Value: !Ref DBPassword
  DBHostParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: '/wordpress/WP_DB_HOST'
      Type: String
      Value: !GetAtt MySQLRDSInstance.Endpoint.Address

Outputs:
  RDSEndpoint:
    Value: !GetAtt MySQLRDSInstance.Endpoint.Address
    Export:
      Name: !Sub 'WpRDSEndpoint'
  DBSecurityGroup:
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub 'WpDbSecurityGroup'